/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboards',
        title: 'Dashboards',
        subtitle: 'Unique dashboard designs',
        type: 'group',
        icon: 'heroicons_outline:home',
        children: [
            {
                id: 'dashboards.home',
                title: 'Home',
                type: 'basic',
                icon: 'heroicons_outline:clipboard-document-check',
                link: '/admin/dashboards/home',
            },
        ],
    },
    {
        id: 'modules',
        title: 'Modules',
        subtitle: 'Unique Modules designs',
        type: 'group',
        icon: 'heroicons_outline:folder-open',
        children: [
            {
                id: 'modules.sitie',
                title: 'Sitie',
                type: 'basic',
                icon: 'heroicons_outline:globe-alt',
                link: '/admin/modules/sitie',
            },
            {
                id: 'modules.microsities',
                title: 'Microsities',
                type: 'basic',
                icon: 'heroicons_outline:queue-list',
                link: '/admin/modules/microsities',
            },
            {
                id: 'modules.pages',
                title: 'Pages',
                type: 'basic',
                icon: 'heroicons_outline:document-duplicate',
                link: '/admin/modules/pages',
            },
            {
                id: 'modules.templates',
                title: 'Templates',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-group',
                link: '/admin/modules/templates',
            },
            {
                id: 'modules.file-manager',
                title: 'File Manager',
                type: 'basic',
                icon: 'heroicons_outline:cloud',
                link: '/admin/modules/file-manager',
            },
        ],
    },
    {
        id: 'entities',
        title: 'Entidades',
        subtitle: 'Unique Entities designs',
        type: 'group',
        icon: 'heroicons_outline:folder-open',
        children: [
            {
                id: 'entities.news',
                title: 'News',
                type: 'basic',
                icon: 'heroicons_outline:newspaper',
                link: '/admin/entities/news',
            },
        ],
    },
    {
        id: 'security',
        title: 'Security',
        subtitle: 'Unique Security designs',
        type: 'group',
        icon: 'heroicons_outline:shield-check',
        children: [
            {
                id: 'security.users',
                title: 'Users',
                type: 'basic',
                icon: 'heroicons_outline:users',
                link: '/admin/security/users',
            },
            {
                id: 'security.parameters',
                title: 'Parameters',
                type: 'basic',
                icon: 'heroicons_outline:adjustments-horizontal',
                link: '/admin/security/parameters',
            },
            {
                id: 'security.settings',
                title: 'Settings',
                type: 'basic',
                icon: 'heroicons_outline:wrench-screwdriver',
                link: '/admin/security/settings',
            },
        ],
    },
];
export const compactNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboards',
        title: 'Dashboards',
        subtitle: 'Unique dashboard designs',
        type: 'group',
        icon: 'heroicons_outline:home',
        children: [
            {
                id: 'dashboards.project',
                title: 'Home',
                type: 'basic',
                icon: 'heroicons_outline:clipboard-document-check',
                link: '/admin/dashboards/home',
            },
        ],
    },
    {
        id: 'modules',
        title: 'Modules',
        subtitle: 'Unique Admin designs',
        type: 'group',
        icon: 'heroicons_outline:folder-open',
        children: [
            {
                id: 'dashboards.project',
                title: 'Sitie',
                type: 'basic',
                icon: 'heroicons_outline:globe-alt',
                link: '/admin/modules/sitie',
            },
            {
                id: 'dashboards.project',
                title: 'Microsities',
                type: 'basic',
                icon: 'heroicons_outline:queue-list',
                link: '/admin/modules/microsities',
            },
            {
                id: 'dashboards.project',
                title: 'Pages',
                type: 'basic',
                icon: 'heroicons_outline:document-duplicate',
                link: '/admin/modules/pages',
            },
            {
                id: 'dashboards.project',
                title: 'Templates',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-group',
                link: '/admin/modules/templates',
            },
            {
                id: 'dashboards.project',
                title: 'File Manager',
                type: 'basic',
                icon: 'heroicons_outline:cloud',
                link: '/admin/modules/file-manager',
            },
        ],
    },
    {
        id: 'security',
        title: 'Security',
        subtitle: 'Unique Security designs',
        type: 'group',
        icon: 'heroicons_outline:shield-check',
        children: [
            {
                id: 'dashboards.project',
                title: 'Users',
                type: 'basic',
                icon: 'heroicons_outline:users',
                link: '/admin/security/users',
            },
            {
                id: 'dashboards.project',
                title: 'Parameters',
                type: 'basic',
                icon: 'heroicons_outline:adjustments-horizontal',
                link: '/admin/security/parameters',
            },
            {
                id: 'dashboards.project',
                title: 'Settings',
                type: 'basic',
                icon: 'heroicons_outline:wrench-screwdriver',
                link: '/admin/security/settings',
            },
        ],
    },
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboards',
        title: 'Dashboards',
        subtitle: 'Unique dashboard designs',
        type: 'group',
        icon: 'heroicons_outline:home',
        children: [
            {
                id: 'dashboards.project',
                title: 'Home',
                type: 'basic',
                icon: 'heroicons_outline:clipboard-document-check',
                link: '/admin/dashboards/home',
            },
        ],
    },
    {
        id: 'modules',
        title: 'Modules',
        subtitle: 'Unique Admin designs',
        type: 'group',
        icon: 'heroicons_outline:folder-open',
        children: [
            {
                id: 'dashboards.project',
                title: 'Sitie',
                type: 'basic',
                icon: 'heroicons_outline:globe-alt',
                link: '/admin/modules/sitie',
            },
            {
                id: 'dashboards.project',
                title: 'Microsities',
                type: 'basic',
                icon: 'heroicons_outline:queue-list',
                link: '/admin/modules/microsities',
            },
            {
                id: 'dashboards.project',
                title: 'Pages',
                type: 'basic',
                icon: 'heroicons_outline:document-duplicate',
                link: '/admin/modules/pages',
            },
            {
                id: 'dashboards.project',
                title: 'Templates',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-group',
                link: '/admin/modules/templates',
            },
            {
                id: 'dashboards.project',
                title: 'File Manager',
                type: 'basic',
                icon: 'heroicons_outline:cloud',
                link: '/admin/modules/file-manager',
            },
        ],
    },
    {
        id: 'security',
        title: 'Security',
        subtitle: 'Unique Security designs',
        type: 'group',
        icon: 'heroicons_outline:shield-check',
        children: [
            {
                id: 'dashboards.project',
                title: 'Users',
                type: 'basic',
                icon: 'heroicons_outline:users',
                link: '/admin/security/users',
            },
            {
                id: 'dashboards.project',
                title: 'Parameters',
                type: 'basic',
                icon: 'heroicons_outline:adjustments-horizontal',
                link: '/admin/security/parameters',
            },
            {
                id: 'dashboards.project',
                title: 'Settings',
                type: 'basic',
                icon: 'heroicons_outline:wrench-screwdriver',
                link: '/admin/security/settings',
            },
        ],
    },
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboards',
        title: 'Dashboards',
        subtitle: 'Unique dashboard designs',
        type: 'group',
        icon: 'heroicons_outline:home',
        children: [
            {
                id: 'dashboards.project',
                title: 'Home',
                type: 'basic',
                icon: 'heroicons_outline:clipboard-document-check',
                link: '/admin/dashboards/home',
            },
        ],
    },
    {
        id: 'modules',
        title: 'Modules',
        subtitle: 'Unique Admin designs',
        type: 'group',
        icon: 'heroicons_outline:folder-open',
        children: [
            {
                id: 'dashboards.project',
                title: 'Sitie',
                type: 'basic',
                icon: 'heroicons_outline:globe-alt',
                link: '/admin/modules/sitie',
            },
            {
                id: 'dashboards.project',
                title: 'Microsities',
                type: 'basic',
                icon: 'heroicons_outline:queue-list',
                link: '/admin/modules/microsities',
            },
            {
                id: 'dashboards.project',
                title: 'Pages',
                type: 'basic',
                icon: 'heroicons_outline:document-duplicate',
                link: '/admin/modules/pages',
            },
            {
                id: 'dashboards.project',
                title: 'Templates',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-group',
                link: '/admin/modules/templates',
            },
            {
                id: 'dashboards.project',
                title: 'File Manager',
                type: 'basic',
                icon: 'heroicons_outline:cloud',
                link: '/admin/modules/file-manager',
            },
        ],
    },
    {
        id: 'security',
        title: 'Security',
        subtitle: 'Unique Security designs',
        type: 'group',
        icon: 'heroicons_outline:shield-check',
        children: [
            {
                id: 'dashboards.project',
                title: 'Users',
                type: 'basic',
                icon: 'heroicons_outline:users',
                link: '/admin/security/users',
            },
            {
                id: 'dashboards.project',
                title: 'Parameters',
                type: 'basic',
                icon: 'heroicons_outline:adjustments-horizontal',
                link: '/admin/security/parameters',
            },
            {
                id: 'dashboards.project',
                title: 'Settings',
                type: 'basic',
                icon: 'heroicons_outline:wrench-screwdriver',
                link: '/admin/security/settings',
            },
        ],
    },
];
